/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.connector.catalog.oracle

import org.apache.spark.sql.connector.catalog.oracle.OracleMetadata.OraColumn
import org.apache.spark.sql.oracle.AbstractTest

class TPCDSTableValidation extends AbstractTest with OraMetadataMgrInternalTest{


  val tblList = Seq("SALES_RANGE_PARTITION",
    "SHIP_MODE",
    "ITEM",
    "CALL_CENTER",
    "CUSTOMER_ADDRESS",
    "WEB_PAGE",
    "CUSTOMER_DEMOGRAPHICS",
    "CATALOG_RETURNS",
    "STORE_RETURNS",
    "INCOME_BAND",
    "WEB_SITE",
    "WEB_SALES",
    "WEB_RETURNS",
    "STORE",
    "DATE_DIM",
    "CATALOG_PAGE",
    "HOUSEHOLD_DEMOGRAPHICS",
    "REASON",
    "STORE_SALES",
    "WAREHOUSE",
    "CATALOG_SALES",
    "PROMOTION",
    "INVENTORY",
    "mixed_case_name",
    "COMP",
    "SALES_BY_REGION_UNKNOWN_VALUES",
    "MIXED_CASE_NAME",
    "SALES_BY_REGION",
    "SALES_BY_REGION_AND_CHANNEL",
    "QUARTERLY_REGIONAL_SALES",
    "HASH_PARTITION_TABLE",
    "REGIONS",
    "TIME_DIM",
    "CUSTOMER")

  def manualValidateTbl(ns: String, tbl: String) : Unit = {
    val bldr = new StringBuilder
    val ot = mdMgr.oraTable(ns, tbl)
    val dcols = ot.columns.map {
      case OraColumn(nm, oraType, _, _) => s"${nm} ${OraDataType.toOracleType(oraType)}"
    }.mkString(" ")

    val dPartCol = new StringBuilder
    ot.partitionScheme match {
      case Some(a) => a.dump(dPartCol)
      case _ => None
    }

    val dFKey = new StringBuilder
    ot.foreignKeys.map(_.dump(dFKey))

    val dPKey = new StringBuilder
    ot.primaryKey match {
      case Some(a) => a.dump(dPKey)
      case _ => None
    }

    val dProperties = ot.properties.map { c =>
      s"${c._1} ${c._2}"
    }.mkString(" ")

    // scalastyle:off

    val sFKey = (ns, tbl) match {
      case ("sparktest", "COUNTRIES2") => s"""columns=[REGION_ID], referencedTable=(,), referencedColumns=[REGION_ID]""".stripMargin
      case _ => ""
    }

    val sProperties = (ns, tbl) match {
      case ("sparktest", "SPARK_TEST_T1") => s"""ACCESS_DRIVER_TYPE ORACLE_BIGDATA REJECT_LIMIT UNLIMITED DEFAULT_DIRECTORY DATA_PUMP_DIR LOCATION https://objectstorage.us-ashburn-1.oraclecloud.com/n/idlxex3qf8sf/b/SparkTest/o/t1.parquet ACCESS_PARAMETERS com.oracle.bigdata.credential.name=OS_EXT_OCI com.oracle.bigdata.fileformat=PARQUET""".stripMargin
      case ("sparktest", "COUNTRIES2") => s"""Foreign Key : columns=[REGION_ID], referencedTable=(,), referencedColumns=[REGION_ID]""".stripMargin
      case _ => ""
    }

    val sPartCol = (ns, tbl) match {
      case ("tpcds", "CATALOG_RETURNS") => s"Partition Scheme: type=RANGE, columns=[CR_RETURNED_DATE_SK]\n"
      case ("tpcds", "STORE_RETURNS") => s"Partition Scheme: type=RANGE, columns=[SR_RETURNED_DATE_SK]\n"
      case ("tpcds", "WEB_SALES") => s"Partition Scheme: type=RANGE, columns=[WS_SOLD_DATE_SK]\n"
      case ("tpcds", "WEB_RETURNS") => s"Partition Scheme: type=RANGE, columns=[WR_RETURNED_DATE_SK]\n"
      case ("tpcds", "STORE_SALES") => s"Partition Scheme: type=RANGE, columns=[SS_SOLD_DATE_SK]\n"
      case ("tpcds", "CATALOG_SALES") => s"Partition Scheme: type=RANGE, columns=[CS_SOLD_DATE_SK]\n"
      case ("tpcds", "INVENTORY") => s"Partition Scheme: type=RANGE, columns=[INV_DATE_SK]\n"
      case ("sparktest", "COMP") => s"Partition Scheme: type=RANGE, columns=[TSTAMP]\n" +
           s"Sub-Partition Scheme: type=LIST, columns=[DEPTNO]\n"
      case ("sparktest", "SALES_RANGE_PARTITION") => s"Partition Scheme: type=RANGE, columns=[SALE_DATE]\n"
      case ("sparktest", "SALES_BY_REGION_UNKNOWN_VALUES") => s"Partition Scheme: type=LIST, columns=[STATE]\n"
      case ("sparktest", "SALES_BY_REGION") => s"Partition Scheme: type=LIST, columns=[STATE_CODE]\n"
      case ("sparktest", "SALES_BY_REGION_AND_CHANNEL") => s"Partition Scheme: type=LIST, columns=[STATE,CHANNEL]\n"
      case ("sparktest", "QUARTERLY_REGIONAL_SALES") => s"Partition Scheme: type=RANGE, columns=[SALE_DATE]\n" + s"[Sub-Partition Scheme: type=LIST, columns=[STATE_CODE]]\n"
      case ("sparktest", "HASH_PARTITION_TABLE") => s"Partition Scheme: type=HASH, columns=[X]\n"
      case _ => ""
    }

    val scols = tbl match {
      case "SALES_RANGE_PARTITION" => s"""PRODUCT_ID NUMBER(6) CUSTOMER_ID NUMBER CHANNEL_ID CHAR(1) PROMO_ID NUMBER(6) SALE_DATE DATE QUANTITY_SOLD NUMBER AMOUNT_SOLD NUMBER(10, 2)""".stripMargin
      case "SHIP_MODE" => s"""SM_SHIP_MODE_SK NUMBER SM_SHIP_MODE_ID CHAR(16) SM_TYPE CHAR(30) SM_CODE CHAR(10) SM_CARRIER CHAR(20) SM_CONTRACT CHAR(20)""".stripMargin
      case "ITEM" => s"""I_ITEM_SK NUMBER I_ITEM_ID CHAR(16) I_REC_START_DATE DATE I_REC_END_DATE DATE I_ITEM_DESC VARCHAR(200) I_CURRENT_PRICE NUMBER I_WHOLESALE_COST NUMBER I_BRAND_ID NUMBER I_BRAND CHAR(50) I_CLASS_ID NUMBER I_CLASS CHAR(50) I_CATEGORY_ID NUMBER I_CATEGORY CHAR(50) I_MANUFACT_ID NUMBER I_MANUFACT CHAR(50) I_SIZE CHAR(20) I_FORMULATION CHAR(20) I_COLOR CHAR(20) I_UNITS CHAR(10) I_CONTAINER CHAR(10) I_MANAGER_ID NUMBER I_PRODUCT_NAME CHAR(50)""".stripMargin
      case "CALL_CENTER" => s"""CC_CALL_CENTER_SK NUMBER CC_CALL_CENTER_ID CHAR(16) CC_REC_START_DATE DATE CC_REC_END_DATE DATE CC_CLOSED_DATE_SK NUMBER CC_OPEN_DATE_SK NUMBER CC_NAME VARCHAR(50) CC_CLASS VARCHAR(50) CC_EMPLOYEES NUMBER CC_SQ_FT NUMBER CC_HOURS CHAR(20) CC_MANAGER VARCHAR(40) CC_MKT_ID NUMBER CC_MKT_CLASS CHAR(50) CC_MKT_DESC VARCHAR(100) CC_MARKET_MANAGER VARCHAR(40) CC_DIVISION NUMBER CC_DIVISION_NAME VARCHAR(50) CC_COMPANY NUMBER CC_COMPANY_NAME CHAR(50) CC_STREET_NUMBER CHAR(10) CC_STREET_NAME VARCHAR(60) CC_STREET_TYPE CHAR(15) CC_SUITE_NUMBER CHAR(10) CC_CITY VARCHAR(60) CC_COUNTY VARCHAR(30) CC_STATE CHAR(2) CC_ZIP CHAR(10) CC_COUNTRY VARCHAR(20) CC_GMT_OFFSET NUMBER(5, 2) CC_TAX_PERCENTAGE NUMBER(5, 2)""".stripMargin
      case "CUSTOMER_ADDRESS" => s"""CA_ADDRESS_SK NUMBER CA_ADDRESS_ID CHAR(16) CA_STREET_NUMBER CHAR(10) CA_STREET_NAME VARCHAR(60) CA_STREET_TYPE CHAR(15) CA_SUITE_NUMBER CHAR(10) CA_CITY VARCHAR(60) CA_COUNTY VARCHAR(30) CA_STATE CHAR(2) CA_ZIP CHAR(10) CA_COUNTRY VARCHAR(20) CA_GMT_OFFSET NUMBER(5, 2) CA_LOCATION_TYPE CHAR(20)""".stripMargin
      case "WEB_PAGE" => s"""WP_WEB_PAGE_SK NUMBER WP_WEB_PAGE_ID CHAR(16) WP_REC_START_DATE DATE WP_REC_END_DATE DATE WP_CREATION_DATE_SK NUMBER WP_ACCESS_DATE_SK NUMBER WP_AUTOGEN_FLAG CHAR(1) WP_CUSTOMER_SK NUMBER WP_URL VARCHAR(100) WP_TYPE CHAR(50) WP_CHAR_COUNT NUMBER WP_LINK_COUNT NUMBER WP_IMAGE_COUNT NUMBER WP_MAX_AD_COUNT NUMBER""".stripMargin
      case "CUSTOMER_DEMOGRAPHICS" => s"""CD_DEMO_SK NUMBER CD_GENDER CHAR(1) CD_MARITAL_STATUS CHAR(1) CD_EDUCATION_STATUS CHAR(20) CD_PURCHASE_ESTIMATE NUMBER CD_CREDIT_RATING CHAR(10) CD_DEP_COUNT NUMBER CD_DEP_EMPLOYED_COUNT NUMBER CD_DEP_COLLEGE_COUNT NUMBER""".stripMargin
      case "CATALOG_RETURNS" => s"""CR_RETURNED_DATE_SK NUMBER CR_RETURNED_TIME_SK NUMBER CR_ITEM_SK NUMBER CR_REFUNDED_CUSTOMER_SK NUMBER CR_REFUNDED_CDEMO_SK NUMBER CR_REFUNDED_HDEMO_SK NUMBER CR_REFUNDED_ADDR_SK NUMBER CR_RETURNING_CUSTOMER_SK NUMBER CR_RETURNING_CDEMO_SK NUMBER CR_RETURNING_HDEMO_SK NUMBER CR_RETURNING_ADDR_SK NUMBER CR_CALL_CENTER_SK NUMBER CR_CATALOG_PAGE_SK NUMBER CR_SHIP_MODE_SK NUMBER CR_WAREHOUSE_SK NUMBER CR_REASON_SK NUMBER CR_ORDER_NUMBER NUMBER CR_RETURN_QUANTITY NUMBER CR_RETURN_AMOUNT NUMBER CR_RETURN_TAX NUMBER CR_RETURN_AMT_INC_TAX NUMBER CR_FEE NUMBER CR_RETURN_SHIP_COST NUMBER CR_REFUNDED_CASH NUMBER CR_REVERSED_CHARGE NUMBER CR_STORE_CREDIT NUMBER CR_NET_LOSS NUMBER""".stripMargin
      case "STORE_RETURNS" => s"""SR_RETURNED_DATE_SK NUMBER SR_RETURN_TIME_SK NUMBER SR_ITEM_SK NUMBER SR_CUSTOMER_SK NUMBER SR_CDEMO_SK NUMBER SR_HDEMO_SK NUMBER SR_ADDR_SK NUMBER SR_STORE_SK NUMBER SR_REASON_SK NUMBER SR_TICKET_NUMBER NUMBER SR_RETURN_QUANTITY NUMBER SR_RETURN_AMT NUMBER SR_RETURN_TAX NUMBER SR_RETURN_AMT_INC_TAX NUMBER SR_FEE NUMBER SR_RETURN_SHIP_COST NUMBER SR_REFUNDED_CASH NUMBER SR_REVERSED_CHARGE NUMBER SR_STORE_CREDIT NUMBER SR_NET_LOSS NUMBER""".stripMargin
      case "INCOME_BAND" => s"""IB_INCOME_BAND_SK NUMBER IB_LOWER_BOUND NUMBER IB_UPPER_BOUND NUMBER""".stripMargin
      case "WEB_SITE" => s"""WEB_SITE_SK NUMBER WEB_SITE_ID CHAR(16) WEB_REC_START_DATE DATE WEB_REC_END_DATE DATE WEB_NAME VARCHAR(50) WEB_OPEN_DATE_SK NUMBER WEB_CLOSE_DATE_SK NUMBER WEB_CLASS VARCHAR(50) WEB_MANAGER VARCHAR(40) WEB_MKT_ID NUMBER WEB_MKT_CLASS VARCHAR(50) WEB_MKT_DESC VARCHAR(100) WEB_MARKET_MANAGER VARCHAR(40) WEB_COMPANY_ID NUMBER WEB_COMPANY_NAME CHAR(50) WEB_STREET_NUMBER CHAR(10) WEB_STREET_NAME VARCHAR(60) WEB_STREET_TYPE CHAR(15) WEB_SUITE_NUMBER CHAR(10) WEB_CITY VARCHAR(60) WEB_COUNTY VARCHAR(30) WEB_STATE CHAR(2) WEB_ZIP CHAR(10) WEB_COUNTRY VARCHAR(20) WEB_GMT_OFFSET NUMBER(5, 2) WEB_TAX_PERCENTAGE NUMBER(5, 2)""".stripMargin
      case "WEB_SALES" => s"""WS_SOLD_DATE_SK NUMBER WS_SOLD_TIME_SK NUMBER WS_SHIP_DATE_SK NUMBER WS_ITEM_SK NUMBER WS_BILL_CUSTOMER_SK NUMBER WS_BILL_CDEMO_SK NUMBER WS_BILL_HDEMO_SK NUMBER WS_BILL_ADDR_SK NUMBER WS_SHIP_CUSTOMER_SK NUMBER WS_SHIP_CDEMO_SK NUMBER WS_SHIP_HDEMO_SK NUMBER WS_SHIP_ADDR_SK NUMBER WS_WEB_PAGE_SK NUMBER WS_WEB_SITE_SK NUMBER WS_SHIP_MODE_SK NUMBER WS_WAREHOUSE_SK NUMBER WS_PROMO_SK NUMBER WS_ORDER_NUMBER NUMBER WS_QUANTITY NUMBER WS_WHOLESALE_COST NUMBER WS_LIST_PRICE NUMBER WS_SALES_PRICE NUMBER WS_EXT_DISCOUNT_AMT NUMBER WS_EXT_SALES_PRICE NUMBER WS_EXT_WHOLESALE_COST NUMBER WS_EXT_LIST_PRICE NUMBER WS_EXT_TAX NUMBER WS_COUPON_AMT NUMBER WS_EXT_SHIP_COST NUMBER WS_NET_PAID NUMBER WS_NET_PAID_INC_TAX NUMBER WS_NET_PAID_INC_SHIP NUMBER WS_NET_PAID_INC_SHIP_TAX NUMBER WS_NET_PROFIT NUMBER""".stripMargin
      case "WEB_RETURNS" => s"""WR_RETURNED_DATE_SK NUMBER WR_RETURNED_TIME_SK NUMBER WR_ITEM_SK NUMBER WR_REFUNDED_CUSTOMER_SK NUMBER WR_REFUNDED_CDEMO_SK NUMBER WR_REFUNDED_HDEMO_SK NUMBER WR_REFUNDED_ADDR_SK NUMBER WR_RETURNING_CUSTOMER_SK NUMBER WR_RETURNING_CDEMO_SK NUMBER WR_RETURNING_HDEMO_SK NUMBER WR_RETURNING_ADDR_SK NUMBER WR_WEB_PAGE_SK NUMBER WR_REASON_SK NUMBER WR_ORDER_NUMBER NUMBER WR_RETURN_QUANTITY NUMBER WR_RETURN_AMT NUMBER WR_RETURN_TAX NUMBER WR_RETURN_AMT_INC_TAX NUMBER WR_FEE NUMBER WR_RETURN_SHIP_COST NUMBER WR_REFUNDED_CASH NUMBER WR_REVERSED_CHARGE NUMBER WR_ACCOUNT_CREDIT NUMBER WR_NET_LOSS NUMBER""".stripMargin
      case "STORE" => s"""S_STORE_SK NUMBER S_STORE_ID CHAR(16) S_REC_START_DATE DATE S_REC_END_DATE DATE S_CLOSED_DATE_SK NUMBER S_STORE_NAME VARCHAR(50) S_NUMBER_EMPLOYEES NUMBER S_FLOOR_SPACE NUMBER S_HOURS CHAR(20) S_MANAGER VARCHAR(40) S_MARKET_ID NUMBER S_GEOGRAPHY_CLASS VARCHAR(100) S_MARKET_DESC VARCHAR(100) S_MARKET_MANAGER VARCHAR(40) S_DIVISION_ID NUMBER S_DIVISION_NAME VARCHAR(50) S_COMPANY_ID NUMBER S_COMPANY_NAME VARCHAR(50) S_STREET_NUMBER VARCHAR(10) S_STREET_NAME VARCHAR(60) S_STREET_TYPE CHAR(15) S_SUITE_NUMBER CHAR(10) S_CITY VARCHAR(60) S_COUNTY VARCHAR(30) S_STATE CHAR(2) S_ZIP CHAR(10) S_COUNTRY VARCHAR(20) S_GMT_OFFSET NUMBER(5, 2) S_TAX_PERCENTAGE NUMBER(5, 2)""".stripMargin
      case "DATE_DIM" => s"""D_DATE_SK NUMBER D_DATE_ID CHAR(16) D_DATE DATE D_MONTH_SEQ NUMBER D_WEEK_SEQ NUMBER D_QUARTER_SEQ NUMBER D_YEAR NUMBER D_DOW NUMBER D_MOY NUMBER D_DOM NUMBER D_QOY NUMBER D_FY_YEAR NUMBER D_FY_QUARTER_SEQ NUMBER D_FY_WEEK_SEQ NUMBER D_DAY_NAME CHAR(9) D_QUARTER_NAME CHAR(6) D_HOLIDAY CHAR(1) D_WEEKEND CHAR(1) D_FOLLOWING_HOLIDAY CHAR(1) D_FIRST_DOM NUMBER D_LAST_DOM NUMBER D_SAME_DAY_LY NUMBER D_SAME_DAY_LQ NUMBER D_CURRENT_DAY CHAR(1) D_CURRENT_WEEK CHAR(1) D_CURRENT_MONTH CHAR(1) D_CURRENT_QUARTER CHAR(1) D_CURRENT_YEAR CHAR(1)""".stripMargin
      case "CATALOG_PAGE" => s"""CP_CATALOG_PAGE_SK NUMBER CP_CATALOG_PAGE_ID CHAR(16) CP_START_DATE_SK NUMBER CP_END_DATE_SK NUMBER CP_DEPARTMENT VARCHAR(50) CP_CATALOG_NUMBER NUMBER CP_CATALOG_PAGE_NUMBER NUMBER CP_DESCRIPTION VARCHAR(100) CP_TYPE VARCHAR(100)""".stripMargin
      case "HOUSEHOLD_DEMOGRAPHICS" => s"""HD_DEMO_SK NUMBER HD_INCOME_BAND_SK NUMBER HD_BUY_POTENTIAL CHAR(15) HD_DEP_COUNT NUMBER HD_VEHICLE_COUNT NUMBER""".stripMargin
      case "REASON" => s"""R_REASON_SK NUMBER R_REASON_ID CHAR(16) R_REASON_DESC CHAR(100)"""
      case "STORE_SALES" =>   s"""SS_SOLD_DATE_SK NUMBER SS_SOLD_TIME_SK NUMBER SS_ITEM_SK NUMBER SS_CUSTOMER_SK NUMBER SS_CDEMO_SK NUMBER SS_HDEMO_SK NUMBER SS_ADDR_SK NUMBER SS_STORE_SK NUMBER SS_PROMO_SK NUMBER SS_TICKET_NUMBER NUMBER SS_QUANTITY NUMBER SS_WHOLESALE_COST NUMBER SS_LIST_PRICE NUMBER SS_SALES_PRICE NUMBER SS_EXT_DISCOUNT_AMT NUMBER SS_EXT_SALES_PRICE NUMBER SS_EXT_WHOLESALE_COST NUMBER SS_EXT_LIST_PRICE NUMBER SS_EXT_TAX NUMBER SS_COUPON_AMT NUMBER SS_NET_PAID NUMBER SS_NET_PAID_INC_TAX NUMBER SS_NET_PROFIT NUMBER""".stripMargin
      case "WAREHOUSE" => s"""W_WAREHOUSE_SK NUMBER W_WAREHOUSE_ID CHAR(16) W_WAREHOUSE_NAME VARCHAR(20) W_WAREHOUSE_SQ_FT NUMBER W_STREET_NUMBER CHAR(10) W_STREET_NAME VARCHAR(60) W_STREET_TYPE CHAR(15) W_SUITE_NUMBER CHAR(10) W_CITY VARCHAR(60) W_COUNTY VARCHAR(30) W_STATE CHAR(2) W_ZIP CHAR(10) W_COUNTRY VARCHAR(20) W_GMT_OFFSET NUMBER(5, 2)""".stripMargin
      case "CATALOG_SALES" => s"""CS_SOLD_DATE_SK NUMBER CS_SOLD_TIME_SK NUMBER CS_SHIP_DATE_SK NUMBER CS_BILL_CUSTOMER_SK NUMBER CS_BILL_CDEMO_SK NUMBER CS_BILL_HDEMO_SK NUMBER CS_BILL_ADDR_SK NUMBER CS_SHIP_CUSTOMER_SK NUMBER CS_SHIP_CDEMO_SK NUMBER CS_SHIP_HDEMO_SK NUMBER CS_SHIP_ADDR_SK NUMBER CS_CALL_CENTER_SK NUMBER CS_CATALOG_PAGE_SK NUMBER CS_SHIP_MODE_SK NUMBER CS_WAREHOUSE_SK NUMBER CS_ITEM_SK NUMBER CS_PROMO_SK NUMBER CS_ORDER_NUMBER NUMBER CS_QUANTITY NUMBER CS_WHOLESALE_COST NUMBER CS_LIST_PRICE NUMBER CS_SALES_PRICE NUMBER CS_EXT_DISCOUNT_AMT NUMBER CS_EXT_SALES_PRICE NUMBER CS_EXT_WHOLESALE_COST NUMBER CS_EXT_LIST_PRICE NUMBER CS_EXT_TAX NUMBER CS_COUPON_AMT NUMBER CS_EXT_SHIP_COST NUMBER CS_NET_PAID NUMBER CS_NET_PAID_INC_TAX NUMBER CS_NET_PAID_INC_SHIP NUMBER CS_NET_PAID_INC_SHIP_TAX NUMBER CS_NET_PROFIT NUMBER""".stripMargin
      case "PROMOTION" => s"""P_PROMO_SK NUMBER P_PROMO_ID CHAR(16) P_START_DATE_SK NUMBER P_END_DATE_SK NUMBER P_ITEM_SK NUMBER P_COST NUMBER(15, 2) P_RESPONSE_TARGET NUMBER P_PROMO_NAME CHAR(50) P_CHANNEL_DMAIL CHAR(1) P_CHANNEL_EMAIL CHAR(1) P_CHANNEL_CATALOG CHAR(1) P_CHANNEL_TV CHAR(1) P_CHANNEL_RADIO CHAR(1) P_CHANNEL_PRESS CHAR(1) P_CHANNEL_EVENT CHAR(1) P_CHANNEL_DEMO CHAR(1) P_CHANNEL_DETAILS VARCHAR(100) P_PURPOSE CHAR(15) P_DISCOUNT_ACTIVE CHAR(1)""".stripMargin
      case "INVENTORY" => s"""INV_DATE_SK NUMBER INV_ITEM_SK NUMBER INV_WAREHOUSE_SK NUMBER INV_QUANTITY_ON_HAND NUMBER""".stripMargin
      case "mixed_case_name" => s"""NAME VARCHAR(100)"""
      case "COMP" => s"""TSTAMP TIMESTAMP(6) EMPNO NUMBER(10) ENAME VARCHAR(10) DEPTNO VARCHAR(10)""".stripMargin
      case "SALES_BY_REGION_UNKNOWN_VALUES" => s"""DEPT_NUMBER NUMBER DEPT_NAME VARCHAR(20) QUARTERLY_SALES NUMBER(10, 2) STATE VARCHAR(2)""".stripMargin
      case "MIXED_CASE_NAME" => s"""NAME VARCHAR(100)"""
      case "SALES_BY_REGION" => s"""ITEM_ID NUMBER ITEM_QUANTITY NUMBER STORE_NAME VARCHAR(30) STATE_CODE VARCHAR(2) SALE_DATE DATE""".stripMargin
      case "SALES_BY_REGION_AND_CHANNEL" => s"""DEPT_NUMBER NUMBER DEPT_NAME VARCHAR(20) QUARTERLY_SALES NUMBER(10, 2) STATE VARCHAR(2) CHANNEL VARCHAR(1)""".stripMargin
      case "QUARTERLY_REGIONAL_SALES" => s"""PRODUCT_ID NUMBER(6) CUSTOMER_ID NUMBER CHANNEL_ID CHAR(1) PROMO_ID NUMBER(6) SALE_DATE DATE QUANTITY_SOLD NUMBER AMOUNT_SOLD NUMBER(10, 2) STORE_NAME VARCHAR(30) STATE_CODE VARCHAR(2)""".stripMargin
      case "HASH_PARTITION_TABLE" => s"""X NUMBER(10)"""
      case "REGIONS" => s"""REGION_ID NUMBER REGION_NAME VARCHAR(25)"""
      case "TIME_DIM" => s"""T_TIME_SK NUMBER T_TIME_ID CHAR(16) T_TIME NUMBER T_HOUR NUMBER T_MINUTE NUMBER T_SECOND NUMBER T_AM_PM CHAR(2) T_SHIFT CHAR(20) T_SUB_SHIFT CHAR(20) T_MEAL_TIME CHAR(20)"""
      case "CUSTOMER" => s"""C_CUSTOMER_SK NUMBER C_CUSTOMER_ID CHAR(16) C_CURRENT_CDEMO_SK NUMBER C_CURRENT_HDEMO_SK NUMBER C_CURRENT_ADDR_SK NUMBER C_FIRST_SHIPTO_DATE_SK NUMBER C_FIRST_SALES_DATE_SK NUMBER C_SALUTATION CHAR(10) C_FIRST_NAME CHAR(20) C_LAST_NAME CHAR(30) C_PREFERRED_CUST_FLAG CHAR(1) C_BIRTH_DAY NUMBER C_BIRTH_MONTH NUMBER C_BIRTH_YEAR NUMBER C_BIRTH_COUNTRY VARCHAR(20) C_LOGIN CHAR(13) C_EMAIL_ADDRESS CHAR(50) C_LAST_REVIEW_DATE_SK NUMBER"""
      case _ => ""
    }
    // scalastyle:on
    assert(dcols == scols, s"Columns For Table ${ns}.${tbl}")
    // assert(dPartCol.mkString == sPartCol, s"Partition Columns For Table ${ns}.${tbl}")
    // assert(dFKey.mkString == sFKey, s"Foreign Key For Table ${ns}.${tbl}")

    // TODO for Primary Key
    // assert(dPKey.mkString == sPKey, s"Foreign Key For Table ${ns}.${tbl}")
    // assert(dProperties == sProperties, s"Properties For Table ${ns}.${tbl}")
  }

  test("ValidateTPCDSTables") { td =>
    for ((ns, tbls) <- catalogTableMap;
         tbl <- tbls) {
      // scalastyle:off
      (ns.toLowerCase(), tbl) match {
        case ((("sparktest") | ("tpcds")), t) => if (tblList.contains(t)) {
          manualValidateTbl(ns, tbl)
        } else {
          println(s"Skipping Table $ns . $tbl .")
        }
        case _ => println(s"Skipping Table $ns . $tbl .")
      }
      // scalastyle:on
    }
  }
}
